# Generated by Django 5.1.15 on 2026-10-06 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('unit', models.CharField(max_length=20)),
                ('stock', models.IntegerField(default=0)),
                ('min_stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LetterCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=20)),
                ('period', models.CharField(max_length=6)),
                ('last', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('kind', 'period')},
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('berobat', 'Berobat'), ('kecelakaan_kerja', 'Kecelakaan kerja'), ('pemeriksaan', 'Pemeriksaan'), ('kehamilan', 'Pemeriksaan kehamilan')], db_index=True, max_length=20)),
                ('visit_at', models.DateTimeField(db_index=True)),
                ('complaint', models.TextField(blank=True)),
                ('exam', models.JSONField(default=dict)),
                ('treatment', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('diagnosis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='poli.diagnosis')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_records', to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poli.medicine')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='poli.medicalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True)),
                ('facility', models.CharField(max_length=150)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(default='diajukan', max_length=20)),
                ('outcome', models.TextField(blank=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poli.medicalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='SickLeaveLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poli.medicalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('reason', models.CharField(max_length=30)),
                ('ref', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='poli.medicine')),
            ],
        ),
    ]
