# Generated by Django 5.1.15 on 2026-10-07 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poli', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordAddendum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='referral',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='note',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='referral',
            name='status',
            field=models.CharField(choices=[('diajukan', 'Diajukan'), ('dirujuk', 'Dirujuk'), ('selesai', 'Selesai'), ('batal', 'Dibatalkan')], db_index=True, default='diajukan', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='medicine_stock_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.CheckConstraint(condition=models.Q(('min_stock__gte', 0)), name='medicine_min_stock_gte_0'),
        ),
        migrations.AddField(
            model_name='recordaddendum',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recordaddendum',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addenda', to='poli.medicalrecord'),
        ),
    ]
