# Generated by Django 5.1.15 on 2026-10-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poli', '0003_diagnosis_medicine_prescription_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sickleaveletter',
            name='days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sickleaveletter',
            name='kind',
            field=models.CharField(choices=[('izin_pulang', 'Surat izin pulang'), ('izin_libur', 'Surat izin libur / istirahat'), ('izin_hamil', 'Surat izin hamil')], default='izin_pulang', max_length=20),
        ),
        migrations.AddField(
            model_name='sickleaveletter',
            name='purpose',
            field=models.CharField(blank=True, choices=[('kontrol', 'Kontrol kehamilan'), ('ringan', 'Keringanan tugas'), ('cuti_melahirkan', 'Rekomendasi cuti melahirkan')], max_length=20),
        ),
        migrations.AddField(
            model_name='sickleaveletter',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='sickleaveletter',
            constraint=models.UniqueConstraint(fields=('record', 'kind'), name='uniq_letter_record_kind'),
        ),
        migrations.AddConstraint(
            model_name='sickleaveletter',
            constraint=models.CheckConstraint(condition=models.Q(('days__isnull', True), models.Q(('days__gte', 1), ('days__lte', 365)), _connector='OR'), name='letter_days_range'),
        ),
    ]
