# Generated by Django 5.2.18 on 2026-10-09 03:48

import apps.core.crypto
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0008_md_group_codes_hours_rotation"),
        ("poli", "0004_letters_by_kind"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("rs", "Rumah sakit"),
                            ("klinik", "Klinik"),
                            ("lab", "Laboratorium"),
                            ("apotek", "Apotek"),
                            ("optik", "Optik"),
                            ("lainnya", "Lainnya"),
                        ],
                        default="klinik",
                        max_length=10,
                    ),
                ),
                ("contact", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PartnerBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bill_number", models.CharField(max_length=40)),
                ("bill_date", models.DateField()),
                ("service_date", models.DateField()),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("rawat_jalan", "Rawat jalan"),
                            ("rawat_inap", "Rawat inap"),
                            ("lab", "Laboratorium"),
                            ("obat", "Obat / apotek"),
                            ("kacamata", "Kacamata / optik"),
                            ("lainnya", "Lainnya"),
                        ],
                        default="rawat_jalan",
                        max_length=12,
                    ),
                ),
                ("complaint", apps.core.crypto.EncryptedTextField(blank=True)),
                (
                    "payer",
                    models.CharField(
                        choices=[
                            ("perusahaan", "Perusahaan"),
                            ("bpjs", "BPJS"),
                            ("karyawan", "Karyawan"),
                        ],
                        default="perusahaan",
                        max_length=10,
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "lines_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("diterima", "Diterima"),
                            ("diverifikasi", "Diverifikasi"),
                            ("disetujui", "Disetujui bayar"),
                            ("dibayar", "Dibayar"),
                            ("ditolak", "Ditolak"),
                        ],
                        db_index=True,
                        default="diterima",
                        max_length=12,
                    ),
                ),
                ("status_note", models.CharField(blank=True, max_length=300)),
                ("paid_date", models.DateField(blank=True, null=True)),
                ("payment_ref", models.CharField(blank=True, max_length=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "diagnosis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="poli.diagnosis",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="partner_bills",
                        to="hr.employee",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bills",
                        to="poli.partner",
                    ),
                ),
            ],
            options={
                "ordering": ["-service_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PartnerBillEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=12)),
                ("to_status", models.CharField(max_length=12)),
                ("note", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="poli.partnerbill",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="PartnerBillLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                ("qty", models.PositiveIntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=14)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="poli.partnerbill",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="partnerbill",
            index=models.Index(
                fields=["service_date"], name="poli_partne_service_fe3942_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partnerbill",
            index=models.Index(
                fields=["partner", "status"], name="poli_partne_partner_89582f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="partnerbill",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ditolak"), _negated=True),
                fields=("partner", "bill_number"),
                name="uniq_partner_bill_number_live",
            ),
        ),
        migrations.AddConstraint(
            model_name="partnerbill",
            constraint=models.CheckConstraint(
                condition=models.Q(("lines_total__gte", 0), ("total_amount__gt", 0)),
                name="partner_bill_amounts",
            ),
        ),
        migrations.AddConstraint(
            model_name="partnerbillline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("amount__gte", 0), ("qty__gte", 1), ("unit_price__gte", 0)
                ),
                name="partner_bill_line_valid",
            ),
        ),
    ]
