# Generated by Django 5.2.18 on 2026-10-10 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0010_extra_work_types"),
        ("poli", "0005_partner_billing"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalrecord",
            name="doctor_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="Dokter"),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="examiner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="examined_records",
                to="hr.employee",
            ),
        ),
    ]
