# Generated by Django 5.2.18 on 2026-10-10 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_extra_work_types'),
        ('poli', '0006_record_examiner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substance', models.CharField(max_length=100, verbose_name='Alergen')),
                ('reaction', models.CharField(blank=True, max_length=200, verbose_name='Reaksi')),
                ('severity', models.CharField(choices=[('ringan', 'Ringan'), ('sedang', 'Sedang'), ('berat', 'Berat')], default='sedang', max_length=10, verbose_name='Tingkat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allergies', to='hr.employee')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['employee', 'voided_at'], name='poli_patien_employe_c6d572_idx')],
            },
        ),
    ]
