# Generated by Django 5.1.15 on 2026-10-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='announcement',
            name='attachment',
            field=models.FileField(blank=True, upload_to='announcements/%Y/%m/'),
        ),
    ]
