# Generated by Django 5.1.15 on 2026-10-06 14:41

import apps.core.crypto
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_announcement_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='delete_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='employee',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank_account',
            field=apps.core.crypto.EncryptedTextField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bpjs_kes',
            field=apps.core.crypto.EncryptedTextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bpjs_tk',
            field=apps.core.crypto.EncryptedTextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nik_ktp',
            field=apps.core.crypto.EncryptedTextField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='employee',
            name='npwp',
            field=apps.core.crypto.EncryptedTextField(blank=True, max_length=25),
        ),
    ]
