# Generated by Django 5.1.15 on 2026-10-06 23:48

import apps.hr.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_employee_encryption_softdelete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ktp', 'KTP'), ('kk', 'Kartu Keluarga'), ('ijazah', 'Ijazah'), ('npwp', 'NPWP'), ('bpjs', 'BPJS'), ('kontrak', 'Dokumen kontrak'), ('sertifikat', 'Sertifikat'), ('sp', 'Surat peringatan'), ('lainnya', 'Lainnya')], max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to=apps.hr.models.doc_path)),
                ('original_name', models.CharField(max_length=200)),
                ('size', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('delete_reason', models.CharField(blank=True, max_length=300)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='hr.employee')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
