# Generated by Django 5.1.15 on 2026-10-07 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_employee_documents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('kind', models.CharField(choices=[('grant', 'Jatah tahunan'), ('use', 'Pemakaian cuti'), ('adjust', 'Koreksi')], max_length=10)),
                ('days', models.DecimalField(decimal_places=1, max_digits=5)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_ledger', to='hr.employee')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leave_rows', to='hr.changerequest')),
            ],
            options={
                'ordering': ['-year', '-id'],
                'indexes': [models.Index(fields=['employee', 'year'], name='hr_leaveled_employe_9d90aa_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('request__isnull', False)), fields=('request', 'year', 'kind'), name='uniq_leave_request_year_kind'), models.UniqueConstraint(condition=models.Q(('kind', 'grant')), fields=('employee', 'year'), name='uniq_leave_grant_employee_year'), models.CheckConstraint(condition=models.Q(models.Q(('kind', 'use'), _negated=True), ('days__lt', 0), _connector='OR'), name='leave_use_is_negative')],
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kind', models.CharField(choices=[('shift', 'Shift pengganti'), ('work', 'Masuk (shift reguler)'), ('off', 'Libur')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_overrides', to='hr.employee')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_rows', to='hr.changerequest')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hr.shift')),
            ],
            options={
                'ordering': ['date', 'id'],
                'indexes': [models.Index(fields=['date', 'employee'], name='hr_shiftass_date_7e26ef_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'date'), name='uniq_shift_assignment_employee_date'), models.CheckConstraint(condition=models.Q(models.Q(('kind', 'shift'), ('shift__isnull', False)), models.Q(('kind__in', ['work', 'off']), ('shift__isnull', True)), _connector='OR'), name='shift_assignment_shift_iff_kind_shift')],
            },
        ),
    ]
