# Generated by Django 5.1.15 on 2026-10-08 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_shift_assignment_leave_ledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True, verbose_name='Kode kelompok')),
                ('pattern', models.CharField(choices=[('2_SHIFT', '2 shift (Pagi–Siang)'), ('3_SHIFT', '3 shift / PACK (Pagi–Siang–Malam)')], max_length=8, verbose_name='Pola')),
            ],
            options={
                'ordering': ['pattern', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ShiftRotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['group__pattern', 'weekday', 'group__code'],
            },
        ),
        migrations.AddField(
            model_name='shift',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktif'),
        ),
        migrations.AddField(
            model_name='shift',
            name='code',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Kode'),
        ),
        migrations.AddField(
            model_name='shift',
            name='is_gs',
            field=models.BooleanField(default=False, verbose_name='General shift (GS)'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('code',), name='uniq_shift_code_when_set'),
        ),
        migrations.AddConstraint(
            model_name='shiftgroup',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('code__endswith', '_pack'), ('pattern', '3_SHIFT')), models.Q(('pattern', '2_SHIFT'), models.Q(('code__endswith', '_pack'), _negated=True)), _connector='OR'), name='shift_group_pack_suffix_matches_pattern'),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='hr.shiftgroup', verbose_name='Kelompok shift'),
        ),
        migrations.AddField(
            model_name='shiftrotation',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotation', to='hr.shiftgroup'),
        ),
        migrations.AddField(
            model_name='shiftrotation',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hr.shift'),
        ),
        migrations.AddConstraint(
            model_name='shiftrotation',
            constraint=models.UniqueConstraint(fields=('group', 'weekday'), name='uniq_rotation_group_weekday'),
        ),
        migrations.AddConstraint(
            model_name='shiftrotation',
            constraint=models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='rotation_weekday_0_6'),
        ),
    ]
