# Generated by Django 5.2.18 on 2026-10-09 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_md_group_codes_hours_rotation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('diminta', 'Diminta'), ('dijawab', 'Dijawab Admin'), ('dikembalikan', 'Dikembalikan'), ('diverifikasi', 'Diverifikasi HRD'), ('dibatalkan', 'Dibatalkan')], db_index=True, default='diminta', max_length=20)),
                ('question', models.CharField(blank=True, max_length=300)),
                ('hint', models.CharField(blank=True, max_length=200)),
                ('due_date', models.DateField()),
                ('answer', models.CharField(blank=True, choices=[('hadir', 'Hadir'), ('izin', 'Izin'), ('sakit', 'Sakit'), ('cuti', 'Cuti'), ('alfa', 'Alfa')], max_length=10)),
                ('answer_note', models.CharField(blank=True, max_length=300)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('final_answer', models.CharField(blank=True, choices=[('hadir', 'Hadir'), ('izin', 'Izin'), ('sakit', 'Sakit'), ('cuti', 'Cuti'), ('alfa', 'Alfa')], max_length=10)),
                ('verify_note', models.CharField(blank=True, max_length=300)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('conflict', models.CharField(blank=True, max_length=200)),
                ('cancel_reason', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_checks', to='hr.employee')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceCheckEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(blank=True, max_length=20)),
                ('value', models.CharField(blank=True, max_length=10)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('att', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='hr.attendancecheck')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='attendancecheck',
            index=models.Index(fields=['department', 'status', 'date'], name='hr_attendan_departm_8a04c5_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancecheck',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'dibatalkan'), _negated=True), fields=('employee', 'date'), name='uniq_attcheck_active'),
        ),
    ]
