# Generated by Django 5.2.18 on 2026-10-09 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_attendance_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequest',
            name='type',
            field=models.CharField(choices=[('mutasi_dept', 'mutasi_dept'), ('mutasi_jabatan', 'mutasi_jabatan'), ('promosi', 'promosi'), ('demosi', 'demosi'), ('rotasi', 'rotasi'), ('status', 'status'), ('shift', 'shift'), ('izin', 'izin'), ('cuti', 'cuti'), ('sakit', 'sakit'), ('izin_terlambat', 'izin_terlambat'), ('izin_pulang', 'izin_pulang'), ('izin_khusus', 'izin_khusus'), ('tukar_shift', 'tukar_shift'), ('tukar_libur', 'tukar_libur'), ('standby', 'standby'), ('lembur', 'lembur')], db_index=True, max_length=30),
        ),
    ]
