# Generated by Django 5.1.15 on 2026-10-07 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0004_employee_documents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BpjsStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(choices=[('kes', 'BPJS Kesehatan (K)'), ('tk', 'BPJS Ketenagakerjaan (TK)')], max_length=3)),
                ('old_status', models.CharField(blank=True, max_length=10)),
                ('new_status', models.CharField(choices=[('aktif', 'Aktif'), ('nonaktif', 'Nonaktif')], max_length=10)),
                ('effective_date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bpjs_logs', to='hr.employee')),
            ],
            options={
                'ordering': ['-effective_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('ditunda', 'Ditunda'), ('selesai', 'Selesai')], db_index=True, default='aktif', max_length=10)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Aid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('kematian', 'Kematian keluarga'), ('pernikahan', 'Pernikahan'), ('kelahiran', 'Kelahiran'), ('musibah', 'Musibah (bencana/kebakaran)'), ('rawat_inap', 'Rawat inap'), ('pendidikan', 'Pendidikan'), ('lainnya', 'Lainnya')], db_index=True, max_length=20)),
                ('event_date', models.DateField()),
                ('amount', models.PositiveBigIntegerField(default=0, help_text='Rupiah')),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('diajukan', 'Diajukan'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak'), ('dibayar', 'Dibayar')], db_index=True, default='diajukan', max_length=12)),
                ('decision_note', models.CharField(blank=True, max_length=300)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aids', to='hr.employee')),
            ],
            options={
                'ordering': ['-event_date', '-id'],
                'indexes': [models.Index(fields=['employee', 'kind', 'event_date'], name='hrd_aid_employe_af60ad_idx')],
            },
        ),
        migrations.CreateModel(
            name='BpjsMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(choices=[('kes', 'BPJS Kesehatan (K)'), ('tk', 'BPJS Ketenagakerjaan (TK)')], max_length=3)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('nonaktif', 'Nonaktif')], max_length=10)),
                ('effective_date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bpjs_memberships', to='hr.employee')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['scheme', 'status'], name='hrd_bpjsmem_scheme_843fc0_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'scheme'), name='uniq_bpjs_employee_scheme')],
            },
        ),
        migrations.CreateModel(
            name='CateringOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('meal', models.CharField(choices=[('sarapan', 'Sarapan'), ('siang', 'Makan siang'), ('malam', 'Makan malam'), ('snack', 'Snack / lembur')], max_length=10)),
                ('qty_large', models.PositiveIntegerField(default=0, verbose_name='Tepak besar (dipesan)')),
                ('qty_small', models.PositiveIntegerField(default=0, verbose_name='Tepak kecil (dipesan)')),
                ('received_large', models.PositiveIntegerField(blank=True, null=True)),
                ('received_small', models.PositiveIntegerField(blank=True, null=True)),
                ('price_large', models.PositiveIntegerField(default=0, verbose_name='Harga tepak besar')),
                ('price_small', models.PositiveIntegerField(default=0, verbose_name='Harga tepak kecil')),
                ('vendor', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('dipesan', 'Dipesan'), ('diterima', 'Diterima'), ('batal', 'Dibatalkan')], db_index=True, default='dipesan', max_length=10)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='Kosong = umum / semua departemen', null=True, on_delete=django.db.models.deletion.PROTECT, to='hr.department')),
            ],
            options={
                'ordering': ['-date', 'meal', 'id'],
                'indexes': [models.Index(fields=['date', 'meal'], name='hrd_caterin_date_24bfe5_idx')],
            },
        ),
        migrations.CreateModel(
            name='MaternityLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(verbose_name='Perkiraan lahir (HPL)')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Tanggal lahir sebenarnya')),
                ('state', models.CharField(choices=[('aktif', 'Aktif'), ('selesai', 'Selesai'), ('batal', 'Dibatalkan')], db_index=True, default='aktif', max_length=10)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('cancel_reason', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maternity_leaves', to='hr.employee')),
            ],
            options={
                'ordering': ['-start_date', '-id'],
                'indexes': [models.Index(fields=['state', 'start_date', 'end_date'], name='hrd_materni_state_2ca1ad_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectDailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(db_index=True)),
                ('activity', models.TextField()),
                ('headcount', models.PositiveIntegerField(default=0, help_text='Terisi otomatis bila pekerja diisi lewat NIK')),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='hrd.project')),
                ('workers', models.ManyToManyField(blank=True, related_name='project_logs', to='hr.employee')),
            ],
            options={
                'ordering': ['-work_date', '-id'],
                'indexes': [models.Index(fields=['project', 'work_date'], name='hrd_project_project_d7813a_idx')],
            },
        ),
    ]
