# Generated by Django 5.1.15 on 2026-10-08 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_md_group_codes_hours_rotation'),
        ('hrd', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(db_index=True)),
                ('worker_name', models.CharField(max_length=100)),
                ('activity', models.CharField(max_length=300)),
                ('wage', models.PositiveIntegerField(default=0, help_text='Rupiah (upah hari itu)')),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-work_date', 'worker_name', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WarningLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=40, unique=True)),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'SP 1'), (2, 'SP 2'), (3, 'SP 3')])),
                ('issue_date', models.DateField()),
                ('valid_until', models.DateField()),
                ('violation', models.CharField(max_length=200, verbose_name='Pelanggaran')),
                ('description', models.TextField(blank=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-issue_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='projectwork',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectwork',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='works', to='hrd.project'),
        ),
        migrations.AddField(
            model_name='warningletter',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warningletter',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warning_letters', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='warningletter',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='projectwork',
            index=models.Index(fields=['project', 'work_date'], name='hrd_project_project_accfa6_idx'),
        ),
        migrations.AddIndex(
            model_name='projectwork',
            index=models.Index(fields=['project', 'worker_name'], name='hrd_project_project_43aec0_idx'),
        ),
        migrations.AddIndex(
            model_name='warningletter',
            index=models.Index(fields=['employee', 'level'], name='hrd_warning_employe_57d8ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='warningletter',
            constraint=models.CheckConstraint(condition=models.Q(('level__gte', 1), ('level__lte', 3)), name='warning_level_1_3'),
        ),
        migrations.AddConstraint(
            model_name='warningletter',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__gte', models.F('issue_date'))), name='warning_valid_after_issue'),
        ),
    ]
