# Generated by Django 5.2.18 on 2026-10-08 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_md_group_codes_hours_rotation'),
        ('hrd', '0004_drop_old_recap_shapes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BpjsDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(choices=[('kes', 'BPJS Kesehatan (K)'), ('tk', 'BPJS Ketenagakerjaan (TK)')], max_length=3)),
                ('period', models.CharField(help_text='YYYY-MM', max_length=7)),
                ('employee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('employer_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bpjs_deductions', to='hr.employee')),
            ],
            options={
                'ordering': ['-period', 'scheme', 'employee_id'],
                'indexes': [models.Index(fields=['period', 'scheme'], name='hrd_bpjsded_period_c5574c_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'scheme', 'period'), name='uniq_bpjs_deduction'), models.CheckConstraint(condition=models.Q(('employee_amount__gte', 0), ('employer_amount__gte', 0)), name='bpjs_deduction_nonneg')],
            },
        ),
    ]
