# Generated by Django 5.2.18 on 2026-10-08 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0008_md_group_codes_hours_rotation"),
        ("hrd", "0005_bpjs_deduction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UniformSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("sort", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort", "code"],
            },
        ),
        migrations.CreateModel(
            name="UniformType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UniformRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("L", "Laki-laki"), ("P", "Perempuan")], max_length=1
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("effective_from", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["gender", "-effective_from"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("gender", "effective_from"), name="uniq_uniform_rate"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("amount__gte", 0)),
                        name="uniform_rate_nonneg",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UniformPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchase_date", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("L", "Laki-laki"), ("P", "Perempuan")], max_length=1
                    ),
                ),
                ("quantity", models.PositiveSmallIntegerField()),
                ("rate_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "deduction_amount",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "deduction_status",
                    models.CharField(
                        choices=[
                            ("belum", "Belum dipotong"),
                            ("sudah", "Sudah dipotong"),
                        ],
                        default="belum",
                        max_length=5,
                    ),
                ),
                (
                    "deducted_period",
                    models.CharField(
                        blank=True,
                        help_text="YYYY-MM periode gaji saat dipotong",
                        max_length=7,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=300)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("void_reason", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uniform_purchases",
                        to="hr.employee",
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="hrd.uniformsize",
                    ),
                ),
                (
                    "utype",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="hrd.uniformtype",
                    ),
                ),
            ],
            options={
                "ordering": ["-purchase_date", "-id"],
                "indexes": [
                    models.Index(
                        fields=["purchase_date"], name="hrd_uniform_purchas_01120e_idx"
                    ),
                    models.Index(
                        fields=["deduction_status"],
                        name="hrd_uniform_deducti_5f7191_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("voided_at__isnull", True)),
                        fields=("employee", "purchase_date", "utype", "size"),
                        name="uniq_uniform_purchase_active",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("deduction_amount__gte", 0),
                            ("quantity__gte", 1),
                            ("rate_amount__gte", 0),
                        ),
                        name="uniform_purchase_valid",
                    ),
                ],
            },
        ),
    ]
