# Generated by Django 5.2.18 on 2026-10-09 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd', '0007_uniform_seed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UniformStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='hrd.uniformsize')),
                ('utype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='hrd.uniformtype')),
            ],
            options={
                'ordering': ['utype__name', 'size__sort', 'size__code'],
                'constraints': [models.UniqueConstraint(fields=('utype', 'size'), name='uniq_uniform_stock')],
            },
        ),
        migrations.CreateModel(
            name='UniformStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('masuk', 'Barang masuk'), ('keluar', 'Keluar (pembelian)'), ('batal', 'Kembali (pembelian batal)'), ('koreksi', 'Koreksi stok')], max_length=8)),
                ('quantity', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('movement_date', models.DateField()),
                ('note', models.CharField(blank=True, help_text='Vendor / no. surat jalan / alasan koreksi', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='hrd.uniformpurchase')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='hrd.uniformsize')),
                ('utype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='hrd.uniformtype')),
            ],
            options={
                'ordering': ['-movement_date', '-id'],
                'indexes': [models.Index(fields=['utype', 'size', 'movement_date'], name='hrd_uniform_utype_i_d0ec2f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity', 0), _negated=True), name='uniform_move_nonzero'), models.UniqueConstraint(condition=models.Q(('purchase__isnull', False)), fields=('purchase', 'kind'), name='uniq_uniform_move_purchase_kind')],
            },
        ),
    ]
