# Generated by Django 5.2.18 on 2026-10-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd', '0009_uniform_stock_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniformstock',
            name='min_stock',
            field=models.PositiveIntegerField(default=0, help_text="Ambang minimum (0 = tidak dipantau); saldo di bawahnya ditandai 'menipis'"),
        ),
    ]
