# Generated by Django 5.2.18 on 2026-10-10 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0010_extra_work_types"),
        ("hrd", "0010_uniform_stock_min"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Separation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("resign", "Mengundurkan diri"),
                            ("habis_kontrak", "Habis kontrak"),
                            ("phk", "PHK / diberhentikan"),
                            ("pensiun", "Pensiun"),
                            ("meninggal", "Meninggal dunia"),
                            ("lainnya", "Lainnya"),
                        ],
                        db_index=True,
                        default="resign",
                        max_length=15,
                    ),
                ),
                (
                    "request_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Tanggal mengajukan / diberitahukan",
                    ),
                ),
                (
                    "last_date",
                    models.DateField(
                        db_index=True,
                        verbose_name="Tanggal keluar (hari terakhir kerja)",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Alasan / keterangan"
                    ),
                ),
                ("emp_name", models.CharField(max_length=150)),
                ("department_name", models.CharField(max_length=100)),
                ("position_name", models.CharField(blank=True, max_length=100)),
                ("join_date", models.DateField()),
                (
                    "tali_asih",
                    models.PositiveBigIntegerField(
                        default=0, help_text="Rupiah; 0 = tidak ada"
                    ),
                ),
                (
                    "tali_asih_note",
                    models.CharField(
                        blank=True,
                        help_text="Dasar hitung / keterangan",
                        max_length=200,
                    ),
                ),
                ("tali_asih_paid_on", models.DateField(blank=True, null=True)),
                ("paklaring_number", models.CharField(blank=True, max_length=40)),
                ("paklaring_date", models.DateField(blank=True, null=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status_changed",
                    models.BooleanField(
                        default=False,
                        help_text="True bila sistem yang menonaktifkan karyawan (dipulihkan saat catatan dibatalkan)",
                    ),
                ),
                ("prev_status", models.CharField(blank=True, max_length=20)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("void_reason", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="separations",
                        to="hr.employee",
                    ),
                ),
                (
                    "paklaring_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_date", "-id"],
                "indexes": [
                    models.Index(
                        fields=["last_date", "kind"],
                        name="hrd_separat_last_da_6e8450_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("voided_at__isnull", True)),
                        fields=("employee",),
                        name="uniq_separation_active",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("paklaring_number", ""), _negated=True),
                        fields=("paklaring_number",),
                        name="uniq_paklaring_number",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("last_date__gte", models.F("join_date"))),
                        name="separation_last_after_join",
                    ),
                ],
            },
        ),
    ]
